#! /bin/bash

# GLOBAL VARIABLES FOR INSTALLATION SCRIPT

HOME_DIR=/home/vagrant

# Node Network parameters
CONTROLLER_IP="10.0.0.11"
CONTROLLER_NETMASK="255.255.255.0"
CONTROLLER_NAMESERVERS="8.8.8.8"
CONTROLLER_HOSTNAME="coa-lab"
PROVIDER_INTERFACE_NAME="eth1"
MANAGEMENT_INTERFACE_NAME="enp0s3:1"
INTERNET_INTERFACE_NAME="enp0s3"
OVERLAY_INTERFACE_IP_ADDRESS=$CONTROLLER_IP

# OpenStack Network Parameters
PROVIDER_NETWORK_TYPE="flat"
PROVIDER_PHYSICAL_NETWORK="provider"
PROVIDER_SUBNET_RANGE="203.0.113.0/24"
PROVIDER_SUBNET_ALLOCATION_START="203.0.113.2"
PROVIDER_SUBNET_ALLOCATION_END="203.0.113.254"
PROVIDER_SUBNET_DNS_SERVER="8.8.8.8"
DEMO_NET_SUBNET_RANGE="192.168.100.0/24"
DEMO_NET_SUBNET_ALLOCATION_START="192.168.100.2"
DEMO_NET_SUBNET_ALLOCATION_END="192.168.100.254"
DEMO_NET_SUBNET_DNS_SERVER="8.8.8.8"

# Passwords
COMMON_PASSWORD="openstack"
RABBIT_PASS=$COMMON_PASSWORD
KEYSTONE_DBPASS=$COMMON_PASSWORD
GLANCE_DBPASS=$COMMON_PASSWORD
GLANCE_PASS=$COMMON_PASSWORD
NOVA_DBPASS=$COMMON_PASSWORD
NOVA_PASS=$COMMON_PASSWORD
PLACEMENT_PASS=$COMMON_PASSWORD
NEUTRON_DBPASS=$COMMON_PASSWORD
NEUTRON_PASS=$COMMON_PASSWORD
SWIFT_PASS=$COMMON_PASSWORD
CINDER_DBPASS=$COMMON_PASSWORD
CINDER_PASS=$COMMON_PASSWORD
HEAT_DBPASS=$COMMON_PASSWORD
HEAT_PASS=$COMMON_PASSWORD
BARBICAN_DBPASS=$COMMON_PASSWORD
BARBICAN_PASS=$COMMON_PASSWORD
METADATA_SECRET=$COMMON_PASSWORD
ADMIN_PASS=$COMMON_PASSWORD
DEMO_PASS=$COMMON_PASSWORD

# NOVNC Proxy base URL for VirtualBox with Forwarded Ports 6080->6080
NOVNCPROXY_BASE_URL="http://localhost:6080/vnc_auto.html"

# Swift devices

SWIFT_DEV_1_1=dm-0
SWIFT_DEV_1_2=dm-1
SWIFT_DEV_2_1=dm-2
SWIFT_DEV_2_2=dm-3

# Cinder devices

CINDER_VOL1=dm-4
CINDER_VOL2=dm-5
